mutation updateFintechData(
  $id: ID!
  $token: String!
  $username: String
  $password: String
  $company_name: String!
  $description: String!
  $min_interest: Float!
  $max_interest: Float!
  $logoURL: String!
  $total_application: Int
  $avg_credit_score: String
  $percent_acceptance: Float
) {
  updateFintechData(
    id: $id
    token: $token
    username: $username
    password: $password
    company_name: $company_name
    description: $description
    min_interest: $min_interest
    max_interest: $max_interest
    logoURL: $logoURL
    total_application: $total_application
    avg_credit_score: $avg_credit_score
    percent_acceptance: $percent_acceptance
  ) {
    _id
    username
    password
    company_name
    description
    min_interest
    max_interest
    logoURL
    total_application
    avg_credit_score
    percent_acceptance
  }
}
